services:
  # Services can be built and launched using (but not limited to) the following commands:
  # docker compose --profile chatservers up --build
  # docker compose --profile addressingserver up --build
  # docker compose --profile client create --build
  # docker compose run --rm --service-ports client

  # Service for the initial Primary Addressing Server
  addressingserver:
    image: addressingserver:latest
    profiles: [ "addressingserver", "main-single" ]
    build:
      dockerfile: Dockerfile.addressingserver
    restart: on-failure
    environment:
      # Defaults to hardcoded values if no .env file is present
      - AS_CLIENT_PORT=${AS_CLIENT_PORT:-49800}
      - AS_REPLICA_PORT=${AS_REPLICA_PORT:-49801}
      - AS_CHATSERVER_PORT=${AS_CHATSERVER_PORT:-49802}
      - HOST_ADDRESS=${PRIMARY_ADDRESS_SERVER_IP:-addressingserver}
      - PUBLIC_ADDRESS=addressingserver
      - AS_ROLE=${AS_ROLE:-PRIMARY}
      - PRIMARY_PEER_PORT=${AS_REPLICA_PORT:-49801}
    ports:
      # Static port mapping for the Primary Addressing Server
      - "49800:49800"
      - "49801:49801"
      - "49802:49802"
      - "5050:5050"
    networks:
      - chat_network
#    healthcheck:
#      test: [ "CMD", "sh", "/healthcheck.sh" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#    restart: on-failure

  # Service for Replica addressing servers
  addressingserver-backup:
    extends:
      service: addressingserver
    profiles: [ "addressingserver-backup" ]
    environment:
      - AS_ROLE=BACKUP
      - PRIMARY_ADDRESS_SERVER_IP=as-primary # Points to the other container
    ports: !reset []

  chatserver:
    image: chatserver:latest
    profiles: [ "chatserver" ]
    build:
      dockerfile: Dockerfile.chatserver
    environment:
      - CS_PORT=${CS_PORT:-2424}
      - CS_PEER_PORT=${CS_PEER_PORT:-2425}
      - CS_ADDRSERVER_PORT=${CS_ADDRSERVER_PORT:-49802}
      - ADDRESS_SERVER_IP=${PRIMARY_ADDRESS_SERVER_IP:-addressingserver}
      - DEBUG_LEVEL=${DEBUG_LEVEL:-0}
      # We leave PUBLIC_ADDRESS out entirely to ensure the internal Docker DNS is used
    networks:
      - chat_network

  client:
    image: client:latest
    profiles: [ "client" ]
    build:
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - CLIENT_PORT=${CLIENT_PORT:-3000}
      - HOST_ADDRESS=${PRIMARY_ADDRESS_SERVER_IP:-addressingserver}
      - ADDRESS_SERVER_IP=${PRIMARY_ADDRESS_SERVER_IP:-addressingserver}
      - AS_CLIENT_PORT=${AS_CLIENT_PORT:-49800}
    networks:
      - chat_network
    tty: true
    stdin_open: true

networks:
  chat_network:
    driver: "bridge"

# This is different from the volume we define in a service. This is how we can ensure that any data...configs:
# ... that is created during the build or execution of the container(s), IS NOT deleted when the container is removed.
# This is very powerful because it allows us to update our repository (new version), and in turn build new containers...configs:
# ... without losing the data (chat logs) from previous versions.
# volumes:
#   db-data:  # Defines a named volume (currently unused in this config but can be used for persistent storage)