# Build stage
FROM gradle:8-jdk21 AS build

# Set the working directory
WORKDIR /app/

# Copy the project files
COPY . .

# Build the project
RUN gradle buildAddressingServer --no-daemon

# Runtime stage
FROM eclipse-temurin:21-jdk

# Set the working directory
WORKDIR /app/

# # Copy startup script from source (not build)
# COPY startup.sh /app/startup.sh
# RUN chmod +x /app/startup.sh

# Copy the built jar from the build stage
COPY --from=build /app/addressingserver/build/libs/addressingserver.jar /app/addressingserver.jar

# Copy the healthcheck script and make it executable
COPY healthcheck.sh /healthcheck.sh
RUN chmod +x /healthcheck.sh
# Replace the entrypoint with a direct command
ENTRYPOINT ["java", "-jar", "/app/addressingserver.jar"]