# Stage 1: Build the application
FROM gradle:jdk23-alpine AS build
WORKDIR /app
COPY . .
WORKDIR /app/
RUN gradle buildClient

# Stage 2: Run the application
FROM eclipse-temurin:23-jdk
WORKDIR /app
COPY --from=build /app/client/build/libs/client.jar /app/client.jar

# Expose the ports the application runs on
ENV CLIENT_PORT=3000
EXPOSE ${CLIENT_PORT}

# Defines the default program run by the Docker Container
CMD ["java", "-jar", "client.jar"]