services:  # Defines the services (Docker containers) that will be run.
          # These not be limited to

  #<name_of_service>: # This is how we declare the "service" aka process we want to create an image of
    #image: chatserver:latest  # The Docker image name and tag used to run this service
    #build:
      #context: ./chatserver  # The directory containing the Dockerfile for building this service
      #dockerfile: Dockerfile  # The specific Dockerfile to use for building the image
    #volumes:
      #- db_data:/var/lib/mysql
    #networks:
      #- chat_network  # Connects this service to the 'chat_network' for communication
    #ports:
      #- "6667:6667"  # Maps port 6667 on the host to port 6667 in the container (used for communication)

  addressingserver:
    image: addressingserver:latest
    container_name: addressingserver
    build:
      context: ./addressingserver
      dockerfile: Dockerfile
    environment:
      - AS_CLIENT_PORT=49800
      - AS_REPLICA_PORT=49801
      - AS_CHATSERVER_PORT=49802
      - HOST_ADDRESS=addressingserver
    networks:
      - chat_network
    ports:
      - "49800-49802:49800-49802"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:49802"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatserver:
    image: chatserver:latest
    container_name: chatserver
    build:
      context: ./chatserver
      dockerfile: Dockerfile
    environment:
      - CS_PORT=2424
      - CS_PEER_PORT=2425
      - CS_ADDRSERVER_PORT=49802
      - HOST_ADDRESS=addressingserver
    depends_on:
      addressingserver:
        condition: service_healthy
    networks:
      - chat_network
    ports:
      - "2424-2426:2424-2426"

  client:
    image: client:latest
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CLIENT_PORT=3000
      - HOST_ADDRESS=client
    depends_on:
      - chatserver
    networks:
      - chat_network
    ports:
      - "3000:3000"

networks:
  chat_network:
    driver: bridge
# This is different from the volume we define in a service. This is how we can ensure that any data...configs:
# ... that is created during the build or execution of the container(s), IS NOT deleted when the container is removed.
# This is very powerful because it allows us to update our repository (new version), and in turn build new containers...configs:
# ... without losing the data (chat logs) from previous versions.
volumes:
  db-data:  # Defines a named volume (currently unused in this config but can be used for persistent storage)
