# Stage 1: Building the jar in a gradle container
FROM gradle:8-jdk21 AS build
# Set the working directory
WORKDIR /app/
# Copy the project files
COPY . .
# Build the project with the Gradle wrapper
RUN gradle buildChatServer --no-daemon
# --info command provides potentially useful debug info. Could also run with --debug i believe
# RUN gradle buildChatServer --no-daemon --info 

# Stage 2: Transferring the product to a runtime container
FROM eclipse-temurin:21-jdk
# Set the working directory
WORKDIR /app
# Copy the built jar from the build stage
COPY --from=build /app/chatserver/build/libs/chatserver.jar /app/chatserver.jar
# Define the default program
ENTRYPOINT ["java", "-jar", "chatserver.jar"]