vrrp_script check_addressingserver {
    script "/usr/local/bin/check_addressing_server.sh"
    interval 2
    weight 2
    fall 2
    rise 2
    user root
    init_fail
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 101
    advert_int 1
    script_security enable  # Add it here instead
    
    authentication {
        auth_type PASS
        auth_pass securepass
    }
    
    virtual_ipaddress {
        172.16.0.2/16
    }
    
    track_script {
        check_addressingserver
    }
}