package io.github.cpsc559.team16.addressingserver;

import io.github.cpsc559.team16.common.dto.AddrServerRecord;
import io.github.cpsc559.team16.common.dto.ChatServerRecord;
import io.github.cpsc559.team16.common.exceptions.ChatServerFullException;
import io.github.cpsc559.team16.common.messaging.BaseAddrServerMessage;
import io.github.cpsc559.team16.common.utilities.NIOMessageChannel;

import java.io.IOException;
import java.nio.channels.SocketChannel;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

public class ChatServerRegistry {

    /**
     * A mapping of unique chat server IDs to their corresponding {@link ChatServerRecord} records.
     * <p>
     * A {@code ChatServerRecord} record is created for each {@code ChatServer},
     * and subsequently updated anytime the {@code ChatServer} reports any changes to its state
     * to the Primary {@code AddressingServer} for each registered chat server in the network.
     * </p>
     */
    private Map<Long, ChatServerRecord> chatServerRecords = new ConcurrentHashMap<>();


    public Map<Long, ChatServerRecord> getRecords() {
        return chatServerRecords;
    }

    /**
     * Replaces the current set of chat server records with the new set of records.
     * <p>
     * This method updates the AddressingServer's registry of chat servers by replacing its internal
     * address log with the new map passed as a parameter. This allows for dynamic reconfiguration or recovery
     * by resetting the chat server records.
     * </p>
     *
     * @param newChatServerRecords a {@code Map} of chat server IDs to {@link ChatServerRecord} objects representing the new address log.
     */
    public void setChatServerRecords(Map<Long, ChatServerRecord> newChatServerRecords) {
        this.chatServerRecords = newChatServerRecords;
    }


    public void putChatServerRecord(Long chatServerPID, ChatServerRecord record) throws IOException {
        this.chatServerRecords.put(chatServerPID, record);
    }

    /**
     * Updates an existing ChatServerRecord if the record being passed in contains
     * a process ID (PID) of a process that has already been registered -
     * otherwise a new record is inserted.
     *
     * @param record The AddrServerRecord to insert or update.
     */
    public void updateOrInsertRecord(ChatServerRecord record) {
        Long id = record.getPID();
        ChatServerRecord existing = chatServerRecords.get(id);

        if (existing != null) {
            System.out.println("Updating existing AddrServerRecord for ID: " + id);
        } else {
            System.out.println("Inserting new AddrServerRecord for ID: " + id);
        }

        chatServerRecords.put(id, record);
        debugPrintAllServers();
    }

    public boolean deregisterServer(Long id) {
        return chatServerRecords.remove(id) != null;
    }

    /**
     * Retrieves the address of an active chat server.
     *
     * @return an {@link Optional} containing the active host address in the format "hostAddress:clientPort",
     *         or {@code Optional.empty()} if no active host exists.
     */
    public Optional<ChatServerRecord> getActiveServer() {
        return chatServerRecords.values().stream()
                .filter(server -> server.getStatus() == ChatServerRecord.ServerStatus.ACTIVE)
                .findFirst();
    }

    public Optional<String> getActiveHost() {
        Optional<ChatServerRecord> activeServer = getActiveServer();

        if (activeServer.isPresent()) {
            ChatServerRecord host = activeServer.get();
            try {
                host.addClient();
            } catch (ChatServerFullException csfe) {
                System.err.printf("Chat Server ID #%d Full - attempting to find another.%n", host.getPID());
                return Optional.empty();
            }
            debugPrintServer(host);
            return Optional.of(host.getHostAddress() + ":" + host.getClientPort());
        }

        return Optional.empty();
    }

    /**
     * Creates a record for a chat server by generating a unique ID and inserting its
     * ChatServerRecord record into the global addressLog.
     * <p>
     * This method generates a unique ID using {@code generatePID()}, creates a new
     * {@link ChatServerRecord} object with the given parameters, and then inserts it into the addressLog. If a record
     * with the same ID already exists, it logs a warning message (and overwrites it).
     * </p>
     *
     * @param serverPID the unique process ID generated by the Primary {@code AddressingServer} for this chat server.
     * @param chatHostAddress the host address (IP or hostname) of the chat server.
     * @param addrServerPort The port used for communication with the addressing server.
     * @param chatClientPort  the port used for client connections.
     * @param chatPeerPort    the port used for peer-to-peer (gossip) communication.
     * @param maxClientCount  the maximum number of client connections allowed for this server.
     *
     * @return serverPID The unique process id generated for the newly registered {@code ChatServer}
     */
    public long createChatServerRecord(Long serverPID, String chatHostAddress, int addrServerPort, int chatClientPort,
                                        int chatPeerPort, int maxClientCount) {
        try {
            ChatServerRecord newServer = new ChatServerRecord(serverPID, chatHostAddress, addrServerPort,
                    chatPeerPort, chatClientPort, maxClientCount);
            // Check if the key already existed (should be null for a new key)
            ChatServerRecord previous = this.chatServerRecords.put(serverPID, newServer);

            if (previous != null) {
                System.err.println("WARNING: A server with ID " + serverPID + " already existed. Overwriting existing entry.");
                // TODO: add logic to skip a range of ID values and re-insert the overwritten record - "previous"
            } else {
                System.out.println("\n**ChatServer** successfully registered with ID: " + serverPID + "\n");
                debugPrintAllServers();
            }
            return serverPID;
        } catch (Exception e) {
            System.err.println("Error registering chat server: " + e.getMessage());
            throw e;
        }
    }


    /**
     * Logs the details of this ChatServerRecord object to the console for debugging purposes.
     */
    public void debugPrintServer(ChatServerRecord s) {
        System.out.println("\t---------- ChatServerRecord Record ----------");
        System.out.printf("\tProcess ID : %s%n", s.getPID());
        System.out.printf("\tHost Address : %s%n", s.getHostAddress());
        System.out.printf("\tClient Port  : %d%n", s.getClientPort());
        System.out.printf("\tPeer Port    : %d%n", s.getPeerPort());
        System.out.printf("\tClient Count : %d%n", s.getClientCount());
        System.out.printf("\tStatus       : %s%n", s.getStatus());
        System.out.println("\t-------------------------------------------");
    }

    public void debugPrintAllServers() {
        System.out.println("|--------------- Currently Registered ChatServer's ---------------|");
        for (ChatServerRecord s : this.chatServerRecords.values()){
            debugPrintServer(s);
        }
        System.out.println("|-----------------------------------------------------------------|");
    }

}
