package io.github.cpsc559.team16.addressingserver;

import io.github.cpsc559.team16.common.exceptions.ChatServerFullException;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

public class ChatServerRegistry {


    /**
     * A mapping of unique chat server IDs to their corresponding {@link ChatServerInfo} records.
     * <p>
     * A {@code ChatServerInfo} record is created for each {@code ChatServer},
     * and subsequently updated anytime the {@code ChatServer} reports any changes to its state
     * to the Primary {@code AddressingServer} for each registered chat server in the network.
     * </p>
     */
    private Map<Long, ChatServerInfo> chatServerRecords = new ConcurrentHashMap<>();


    public Map<Long, ChatServerInfo> getRecords() {
        return chatServerRecords;
    }

    /**
     * Replaces the current set of chat server records with the new set of records.
     * <p>
     * This method updates the AddressingServer's registry of chat servers by replacing its internal
     * address log with the new map passed as a parameter. This allows for dynamic reconfiguration or recovery
     * by resetting the chat server records.
     * </p>
     *
     * @param newChatServerRecords a {@code Map} of chat server IDs to {@link ChatServerInfo} objects representing the new address log.
     */
    public void setChatServerRecords(Map<Long, ChatServerInfo> newChatServerRecords) {
        this.chatServerRecords = newChatServerRecords;
    }


    public void registerServer(Long id, ChatServerInfo record) {
        chatServerRecords.put(id, record);
    }

    public boolean deregisterServer(Long id) {
        return chatServerRecords.remove(id) != null;
    }

    /**
     * Retrieves the address of an active chat server.
     *
     * @return an {@link Optional} containing the active host address in the format "hostAddress:clientPort",
     *         or {@code Optional.empty()} if no active host exists.
     */
    public Optional<ChatServerInfo> getActiveServer() {
        return chatServerRecords.values().stream()
                .filter(server -> server.getStatus() == ChatServerInfo.ServerStatus.ACTIVE)
                .findFirst();
    }

    public Optional<String> getActiveHost() {
        Optional<ChatServerInfo> activeServer = getActiveServer();

        if (activeServer.isPresent()) {
            ChatServerInfo host = activeServer.get();
            try {
                host.addClient();
            } catch (ChatServerFullException csfe) {
                System.err.printf("Chat Server ID #%d Full - attempting to find another.%n", host.getPID());
                return Optional.empty();
            }
            debugPrintServer(host);
            return Optional.of(host.getHostAddress() + ":" + host.getClientPort());
        }

        return Optional.empty();
    }

    /**
     * Creates a record for a chat server by generating a unique ID and inserting its
     * ChatServerInfo record into the global addressLog.
     * <p>
     * This method generates a unique ID using {@code generatePID()}, creates a new
     * {@link ChatServerInfo} object with the given parameters, and then inserts it into the addressLog. If a record
     * with the same ID already exists, it logs a warning message (and overwrites it).
     * </p>
     *
     * @param serverPID the unique process ID generated by the Primary {@code AddressingServer} for this chat server.
     * @param chatHostAddress the host address (IP or hostname) of the chat server.
     * @param addrServerPort The port used for communication with the addressing server.
     * @param chatClientPort  the port used for client connections.
     * @param chatPeerPort    the port used for peer-to-peer (gossip) communication.
     * @param maxClientCount  the maximum number of client connections allowed for this server.
     *
     * @return serverPID The unique process id generated for the newly registered {@code ChatServer}
     */
    public long createChatServerRecord(Long serverPID, String chatHostAddress, int addrServerPort, int chatClientPort,
                                        int chatPeerPort, int maxClientCount) {
        try {
            ChatServerInfo newServer = new ChatServerInfo(serverPID, chatHostAddress, addrServerPort,
                    chatPeerPort, chatClientPort, maxClientCount);
            // Check if the key already existed (should be null for a new key)
            ChatServerInfo previous = this.chatServerRecords.put(serverPID, newServer);

            if (previous != null) {
                System.err.println("WARNING: A server with ID " + serverPID + " already existed. Overwriting existing entry.");
                // TODO: add logic to skip a range of ID values and re-insert the overwritten record - "previous"
            } else {
                System.out.print("\n**ChatServer** registered successfully with ID: %d\n\n" + serverPID);
                debugPrintAllServers();
            }
            return serverPID;
        } catch (Exception e) {
            System.err.println("Error registering chat server: " + e.getMessage());
            throw e;
        }
    }



    /**
     * Logs the details of this ChatServerInfo object to the console for debugging purposes.
     */
    public void debugPrintServer(ChatServerInfo s) {
        System.out.println("---------- ChatServerInfo Debug ----------");
        System.out.printf("Host Address : %s%n", s.getHostAddress());
        System.out.printf("Client Port  : %d%n", s.getClientPort());
        System.out.printf("Peer Port    : %d%n", s.getPeerPort());
        System.out.printf("Client Count : %d%n", s.getClientCount());
        System.out.printf("Status       : %s%n", s.getStatus());
        System.out.println("--------------------------------------");
    }

    public void debugPrintAllServers() {
        for (ChatServerInfo s : this.chatServerRecords.values()){
            System.out.println("---------- Current ChatServerInfo Records ----------");
            System.out.printf("Host Address : %s%n", s.getHostAddress());
            System.out.printf("Client Port  : %d%n", s.getClientPort());
            System.out.printf("Peer Port    : %d%n", s.getPeerPort());
            System.out.printf("Client Count : %d%n", s.getClientCount());
            System.out.printf("Status       : %s%n", s.getStatus());
            System.out.println("----------------------------------------------------");
        }
    }

}
